name: Docker build and push

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mstarongithub/mk-plugin-repo

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          # labels: |
          #   maintainer=mStar;Leah
          #   org.opencontainers.image.title=Misskey Plugin Repository
          #   org.opencontainers.image.url=https://mk-plugins.evilthings.de # TODO: Actually create this subdomain
          #   org.opencontainers.image.source=https://github.com/mstarongithub/mk-plugin-repo
          #   org.opencontainers.image.vendor=Evilthings

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
